### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by pfriesch** [melrief/PureCSV#4] opened 2015-06-23 12:40 UTC
Your example:

``` scala
    import purecsv.safe._
    case class Person(name: String, age: Int)
    val p: List[Try[Person]] = CSVReader[Person].readCSVFromString("alice,1")
```

leads to a compile time error:
`could not find implicit value for parameter rfcImp: purecsv.safe.converter.RawFieldsConverter[Person]`

**Comment by melrief** [comment] 2015-08-16 12:17
I can't reproduce the error, can you tell me where do you run the example? I have just opened a sbt console and the example works:

``` scala
scala> import purecsv.safe._
import purecsv.safe._

scala> case class Person(name: String, age: Int)
defined class Person

scala> CSVReader[Person].readCSVFromString("alice,1")
res0: List[scala.util.Try[Person]] = List(Success(Person(alice,1)))
```

**Comment by cafpereira** [comment] 2015-11-03 20:13
Hi, I am having the same issue. To run the example I am using: Scala 2.10, Java 1.8 and PureCSV 0.0.4, thanks!

``` shell
Welcome to Scala version 2.10.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_31).
Type in expressions to have them evaluated.
Type :help for more information.

scala> import purecsv.safe._
import purecsv.safe._

scala> class Interval(val start: Long, val end: Long)
defined class Interval

scala> new Interval(10,20).toCSV()
<console>:12: error: could not find implicit value for parameter rfc: purecsv.safe.converter.RawFieldsConverter[Interval]
              new Interval(10,20).toCSV()
              ^
```

**Comment by melrief** [comment] 2015-11-03 20:54
@cafpereira I'm not sure why this happens but I can get it work from sbt console:

``` scala
Welcome to Scala version 2.10.5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_60).
Type in expressions to have them evaluated.
Type :help for more information.

scala> import purecsv.safe._
import purecsv.safe._

scala> class Interval(val start: Long, val end: Long)
defined class Interval

scala> new Interval(10,20).toCSV()
res0: String = 10,20
```

I will investigate this further anyway, this is very strange.

EDIT: the problem is using the library in an external project. I'm not sure what's the difference but it's a bug for sure. I will check this more.

**Comment by cafpereira** [comment] 2015-11-03 21:04
thanks @melrief for taking time to check this out.

**Comment by melrief** [comment] 2015-11-03 21:16
I think I made a mistake and forgot to write in the example that you need the macroparadise plugin for sbt when using the library with scala 2.10. Without it, Shapeless can't provide the proper generic instances. @cafpereira can you try adding the compiler plugin in this way

``` scala
    "com.github.melrief" %% "purecsv"    % "0.0.4"
  ,  compilerPlugin("org.scalamacros" % "paradise" % "2.0.1" cross CrossVersion.full)
```

and then try again?

**Comment by cafpereira** [comment] 2015-11-03 21:24
Of course, I just added the compilerPlugin and now its working like a charm!

``` shell
[info] Starting scala interpreter...
[info]
Welcome to Scala version 2.10.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_31).
Type in expressions to have them evaluated.
Type :help for more information.

scala> import purecsv.safe._
import purecsv.safe._

scala> class Interval(val start: Long, val end: Long)
defined class Interval

scala> new Interval(10,20).toCSV()
res0: String = 10,20
```

**Comment by melrief** [comment] 2015-11-03 21:26
I will add it to the README, thanks for trying!

**Comment by cafpereira** [comment] 2015-11-03 21:26
:+1:

**Comment by melrief** [comment] 2015-11-03 21:52
Done, closing this issue.

**Closed as completed by melrief** 2015-11-03 21:52 UTC

**Comment by jkransen** [comment] 2017-02-24 09:28
I am getting the same error when using this: 

    sealed trait Line

    object Line {
      def parse[T <: Line](line: String): T = CSVReader[T].readCSVFromString(line).head
    }

    case class UserLine() extends Line


A simple example like the one on top works fine. Is it a different issue? I did not read anything specific in the README about adding shapeless plugin.

**Comment by suryasev** [comment] 2017-04-14 22:41
I'm getting the same issue with version 0.0.9 and the exact example from the original question.

**Comment by tfedorov** [comment] 2019-02-28 14:30
I have the same problem when I use generic instead of concrete case clase.

```
  def fromCSV[C](path: String) = {
     CSVReader[C].readCSVFromFileName("...")   
  }
```
But the same code works well.
```
 case class CSVRecord(alias: String, second: Int, third: Int, label: Double)
 val r = SVReader[CSVRecord].readCSVFromFileName("./src/main/resources/input_simple_noheader.csv")
```
Do You know how to fix it with generic?

Thank You for help.

**Comment by steveipkis** [comment] 2019-03-28 20:51
> I have the same problem when I use generic instead of concrete case clase.
> 
> ```
>   def fromCSV[C](path: String) = {
>      CSVReader[C].readCSVFromFileName("...")   
>   }
> ```
> But the same code works well.
> 
> ```
>  case class CSVRecord(alias: String, second: Int, third: Int, label: Double)
>  val r = SVReader[CSVRecord].readCSVFromFileName("./src/main/resources/input_simple_noheader.csv")
> ```
> Do You know how to fix it with generic?
> 
> Thank You for help.

Had the same issue as you did and I ended up having to read how it was implemented. So, if you try this below it should work perfectly fine. 

 ```scala
def fromCSV[C](path: String)(implicit rfcImp: RawFieldsConverter[U]) = {
    CSVReader[C].readCSVFromFileName("...")   
}
 ```
